package br.com.view;

import br.com.model.Endereco;
import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;

/**
 *
 * @author deko_
 */
public class ConsultarCep extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCep
     */
    public ConsultarCep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Textcep = new javax.swing.JFormattedTextField();
        Buttonconsultarcep = new javax.swing.JButton();
        Labelresult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Textcep.setText("Digite o cep aqui");

        Buttonconsultarcep.setText("Consultar CEP");
        Buttonconsultarcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonconsultarcepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Labelresult, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buttonconsultarcep)
                    .addComponent(Textcep, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Textcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Buttonconsultarcep)
                .addGap(18, 18, 18)
                .addComponent(Labelresult, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonconsultarcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonconsultarcepActionPerformed
        // TODO add your handling code here:
        try {
            String CONSULTA = Textcep.getText();
            
            URL url = new URL("https://viacep.com.br/ws/"+CONSULTA+"/json");
            HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
            
            // Configurar o método de requisição como GET
            connection.setRequestMethod("GET");
            connection.setRequestProperty("Accept", "application/json");
            
            // Verificar o código de resposta
            int responseCode = connection.getResponseCode();
            if (responseCode == HttpsURLConnection.HTTP_OK) { // 200 OK
                BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream(), "UTF-8"));
                String inputLine;
                StringBuilder response = new StringBuilder();

                // Ler a resposta linha por linha
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
                in.close();
                
                // Converter a resposta JSON em um objeto CepResponse usando Gson
                Gson gson = new Gson();
                Endereco endereco = gson.fromJson(response.toString(), Endereco.class);

                // Exibir os valores individuais
                Labelresult.setText("<HTML>CEP: "+ endereco.getCep()+ "<br>Logradouro: " + endereco.getLogradouro()+"<br>Complemento: " + endereco.getComplemento()
                        +"<br>Unidade: " + endereco.getUnidade()+"<br>Bairro: " + endereco.getBairro()+"<br>Localidade: " + endereco.getLocalidade()
                        +"<br>UF: " + endereco.getUf()+"<br>DDD: " + endereco.getDdd()+"</HTML>");
                
                
                //System.out.println("IBGE: " + endereco.getIbge());
                //System.out.println("GIA: " + endereco.getGia());
                //System.out.println("DDD: " + endereco.getDdd());
                //System.out.println("SIAFI: " + endereco.getSiafi());
            } else {
                System.out.println("Erro na conexão: " + responseCode);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonconsultarcepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonconsultarcep;
    private javax.swing.JLabel Labelresult;
    private javax.swing.JFormattedTextField Textcep;
    // End of variables declaration//GEN-END:variables
}
